// Comprehensive book metadata with proper titles and authors
// Format: "Title - Author (honorific)" in both English and Arabic

export interface BookMetadata {
  id: string;
  titleAr: string;
  titleEn: string;
  authorAr: string;
  authorEn: string;
  volumes?: number;
  century?: number;
  deathYear?: number;
  language?: string;
}

// Comprehensive book metadata mapping by book ID
export const BOOK_METADATA: Record<string, BookMetadata> = {
  // ===== MAJOR HADITH COLLECTIONS =====
  '01407': {
    id: '01407',
    titleAr: 'بحار الأنوار',
    titleEn: 'Bihar al-Anwar',
    authorAr: 'العلامة المجلسي (رحمه الله)',
    authorEn: 'Allamah Majlisi (ra)',
    volumes: 110,
    century: 11,
    deathYear: 1110,
    language: 'ar',
  },
  '01405': {
    id: '01405',
    titleAr: 'وسائل الشيعة',
    titleEn: 'Wasail al-Shia',
    authorAr: 'الحر العاملي (رحمه الله)',
    authorEn: 'Al-Hurr al-Amili (ra)',
    volumes: 30,
    century: 11,
    deathYear: 1104,
    language: 'ar',
  },
  '01348': {
    id: '01348',
    titleAr: 'الكافي',
    titleEn: 'Al-Kafi',
    authorAr: 'الشيخ الكليني (رحمه الله)',
    authorEn: 'Sheikh al-Kulayni (ra)',
    volumes: 8,
    century: 4,
    deathYear: 329,
    language: 'ar',
  },
  '01347': {
    id: '01347',
    titleAr: 'من لا يحضره الفقيه',
    titleEn: 'Man La Yahduruhu al-Faqih',
    authorAr: 'الشيخ الصدوق (رحمه الله)',
    authorEn: 'Sheikh al-Saduq (ra)',
    volumes: 4,
    century: 4,
    deathYear: 381,
    language: 'ar',
  },
  '01346': {
    id: '01346',
    titleAr: 'تهذيب الأحكام',
    titleEn: 'Tahdhib al-Ahkam',
    authorAr: 'الشيخ الطوسي (رحمه الله)',
    authorEn: 'Sheikh al-Tusi (ra)',
    volumes: 10,
    century: 5,
    deathYear: 460,
    language: 'ar',
  },
  '01370': {
    id: '01370',
    titleAr: 'الاستبصار',
    titleEn: 'Al-Istibsar',
    authorAr: 'الشيخ الطوسي (رحمه الله)',
    authorEn: 'Sheikh al-Tusi (ra)',
    volumes: 4,
    century: 5,
    deathYear: 460,
    language: 'ar',
  },
  '01406': {
    id: '01406',
    titleAr: 'مستدرك الوسائل',
    titleEn: 'Mustadrak al-Wasail',
    authorAr: 'الميرزا النوري (رحمه الله)',
    authorEn: 'Mirza al-Nuri (ra)',
    volumes: 18,
    century: 14,
    deathYear: 1320,
    language: 'ar',
  },

  // ===== NAHJ AL-BALAGHA & COMMENTARIES =====
  '14618': {
    id: '14618',
    titleAr: 'نهج البلاغة',
    titleEn: 'Nahj al-Balagha',
    authorAr: 'الشريف الرضي (رحمه الله)',
    authorEn: 'Al-Sharif al-Radi (ra)',
    volumes: 4,
    century: 4,
    deathYear: 406,
    language: 'ar',
  },
  '01484': {
    id: '01484',
    titleAr: 'شرح نهج البلاغة',
    titleEn: 'Sharh Nahj al-Balagha',
    authorAr: 'ابن أبي الحديد المعتزلي',
    authorEn: 'Ibn Abi al-Hadid',
    volumes: 20,
    century: 7,
    deathYear: 656,
    language: 'ar',
  },
  '03502': {
    id: '03502',
    titleAr: 'منهاج البراعة (شرح نهج البلاغة)',
    titleEn: 'Minhaj al-Bara\'a',
    authorAr: 'الميرزا حبيب الله الخوئي (رحمه الله)',
    authorEn: 'Mirza Habibullah al-Khoei (ra)',
    volumes: 21,
    century: 14,
    deathYear: 1324,
    language: 'ar',
  },
  '03513': {
    id: '03513',
    titleAr: 'نهج السعادة في مستدرك نهج البلاغة',
    titleEn: 'Nahj al-Sa\'ada',
    authorAr: 'الشيخ محمد باقر المحمودي',
    authorEn: 'Sheikh Muhammad Baqir al-Mahmudi',
    volumes: 8,
    century: 15,
    language: 'ar',
  },
  '03415': {
    id: '03415',
    titleAr: 'شرح نهج البلاغة',
    titleEn: 'Sharh Nahj al-Balagha',
    authorAr: 'ابن ميثم البحراني (رحمه الله)',
    authorEn: 'Ibn Maytham al-Bahrani (ra)',
    volumes: 5,
    century: 7,
    deathYear: 679,
    language: 'ar',
  },

  // ===== KAFI COMMENTARIES =====
  '10879': {
    id: '10879',
    titleAr: 'شرح أصول الكافي',
    titleEn: 'Sharh Usul al-Kafi',
    authorAr: 'صدر المتألهين الشيرازي (رحمه الله)',
    authorEn: 'Sadr al-Din Shirazi (ra)',
    volumes: 4,
    century: 11,
    deathYear: 1050,
    language: 'ar',
  },
  '03636': {
    id: '03636',
    titleAr: 'مرآة العقول',
    titleEn: 'Mir\'at al-Uqul',
    authorAr: 'العلامة المجلسي (رحمه الله)',
    authorEn: 'Allamah Majlisi (ra)',
    volumes: 26,
    century: 11,
    deathYear: 1110,
    language: 'ar',
  },
  '03639': {
    id: '03639',
    titleAr: 'شرح الكافي',
    titleEn: 'Sharh al-Kafi',
    authorAr: 'المولى محمد صالح المازندراني (رحمه الله)',
    authorEn: 'Mulla Salih al-Mazandarani (ra)',
    volumes: 12,
    century: 11,
    deathYear: 1081,
    language: 'ar',
  },
  '10036': {
    id: '10036',
    titleAr: 'الوافي',
    titleEn: 'Al-Wafi',
    authorAr: 'الفيض الكاشاني (رحمه الله)',
    authorEn: 'Al-Fayd al-Kashani (ra)',
    volumes: 26,
    century: 11,
    deathYear: 1091,
    language: 'ar',
  },
  '03604': {
    id: '03604',
    titleAr: 'ملاذ الأخيار',
    titleEn: 'Maladh al-Akhyar',
    authorAr: 'العلامة المجلسي (رحمه الله)',
    authorEn: 'Allamah Majlisi (ra)',
    volumes: 16,
    century: 11,
    deathYear: 1110,
    language: 'ar',
  },

  // ===== GHURAR AL-HIKAM =====
  '03574': {
    id: '03574',
    titleAr: 'غرر الحكم ودرر الكلم',
    titleEn: 'Ghurar al-Hikam',
    authorAr: 'الآمدي (رحمه الله)',
    authorEn: 'Al-Amidi (ra)',
    volumes: 1,
    century: 6,
    deathYear: 550,
    language: 'ar',
  },
  '02663': {
    id: '02663',
    titleAr: 'شرح غرر الحكم',
    titleEn: 'Sharh Ghurar al-Hikam',
    authorAr: 'آقا جمال الدين الخوانساري (رحمه الله)',
    authorEn: 'Aqa Jamal al-Din al-Khwansari (ra)',
    volumes: 6,
    century: 12,
    deathYear: 1125,
    language: 'ar',
  },

  // ===== TAFSIR (QURAN COMMENTARY) =====
  '01913': {
    id: '01913',
    titleAr: 'مجمع البيان',
    titleEn: 'Majma\' al-Bayan',
    authorAr: 'الشيخ الطبرسي (رحمه الله)',
    authorEn: 'Sheikh al-Tabrisi (ra)',
    volumes: 10,
    century: 6,
    deathYear: 548,
    language: 'ar',
  },
  '01911': {
    id: '01911',
    titleAr: 'البرهان في تفسير القرآن',
    titleEn: 'Al-Burhan fi Tafsir al-Quran',
    authorAr: 'السيد هاشم البحراني (رحمه الله)',
    authorEn: 'Sayyid Hashim al-Bahrani (ra)',
    volumes: 5,
    century: 11,
    deathYear: 1107,
    language: 'ar',
  },
  '01342': {
    id: '01342',
    titleAr: 'تفسير الصافي',
    titleEn: 'Tafsir al-Safi',
    authorAr: 'الفيض الكاشاني (رحمه الله)',
    authorEn: 'Al-Fayd al-Kashani (ra)',
    volumes: 5,
    century: 11,
    deathYear: 1091,
    language: 'ar',
  },
  '01904': {
    id: '01904',
    titleAr: 'تفسير نور الثقلين',
    titleEn: 'Tafsir Nur al-Thaqalayn',
    authorAr: 'الشيخ الحويزي (رحمه الله)',
    authorEn: 'Sheikh al-Huwayzi (ra)',
    volumes: 5,
    century: 11,
    deathYear: 1112,
    language: 'ar',
  },
  '01912': {
    id: '01912',
    titleAr: 'تفسير كنز الدقائق',
    titleEn: 'Tafsir Kanz al-Daqa\'iq',
    authorAr: 'الميرزا محمد المشهدي (رحمه الله)',
    authorEn: 'Mirza Muhammad al-Mashhadi (ra)',
    volumes: 14,
    century: 12,
    deathYear: 1125,
    language: 'ar',
  },
  '11728': {
    id: '11728',
    titleAr: 'التفسير الأثري الجامع',
    titleEn: 'Al-Tafsir al-Athari al-Jami\'',
    authorAr: 'الشيخ محمد هادي معرفت (رحمه الله)',
    authorEn: 'Sheikh Muhammad Hadi Ma\'rifat (ra)',
    volumes: 6,
    century: 15,
    deathYear: 1427,
    language: 'ar',
  },

  // ===== HISTORY & BIOGRAPHY =====
  '01566': {
    id: '01566',
    titleAr: 'مناقب آل أبي طالب',
    titleEn: 'Manaqib Al Abi Talib',
    authorAr: 'ابن شهر آشوب (رحمه الله)',
    authorEn: 'Ibn Shahr Ashub (ra)',
    volumes: 4,
    century: 6,
    deathYear: 588,
    language: 'ar',
  },
  '02383': {
    id: '02383',
    titleAr: 'حياة القلوب',
    titleEn: 'Hayat al-Qulub',
    authorAr: 'العلامة المجلسي (رحمه الله)',
    authorEn: 'Allamah Majlisi (ra)',
    volumes: 3,
    century: 11,
    deathYear: 1110,
    language: 'ar',
  },
  '02414': {
    id: '02414',
    titleAr: 'حلية الأبرار',
    titleEn: 'Hilyat al-Abrar',
    authorAr: 'السيد هاشم البحراني (رحمه الله)',
    authorEn: 'Sayyid Hashim al-Bahrani (ra)',
    volumes: 2,
    century: 11,
    deathYear: 1107,
    language: 'ar',
  },
  '02416': {
    id: '02416',
    titleAr: 'مدينة معاجز الأئمة',
    titleEn: 'Madinat Ma\'ajiz al-A\'imma',
    authorAr: 'السيد هاشم البحراني (رحمه الله)',
    authorEn: 'Sayyid Hashim al-Bahrani (ra)',
    volumes: 8,
    century: 11,
    deathYear: 1107,
    language: 'ar',
  },

  // ===== DUAS & SUPPLICATIONS =====
  '13608': {
    id: '13608',
    titleAr: 'سفينة البحار',
    titleEn: 'Safinat al-Bihar',
    authorAr: 'الشيخ عباس القمي (رحمه الله)',
    authorEn: 'Sheikh Abbas al-Qummi (ra)',
    volumes: 8,
    century: 14,
    deathYear: 1359,
    language: 'ar',
  },
  '13631': {
    id: '13631',
    titleAr: 'مستدرك سفينة البحار',
    titleEn: 'Mustadrak Safinat al-Bihar',
    authorAr: 'الشيخ علي النمازي (رحمه الله)',
    authorEn: 'Sheikh Ali al-Namazi (ra)',
    volumes: 10,
    century: 15,
    deathYear: 1405,
    language: 'ar',
  },
  '02171': {
    id: '02171',
    titleAr: 'رياض السالكين',
    titleEn: 'Riyad al-Salikin',
    authorAr: 'السيد علي خان المدني (رحمه الله)',
    authorEn: 'Sayyid Ali Khan al-Madani (ra)',
    volumes: 7,
    century: 12,
    deathYear: 1120,
    language: 'ar',
  },

  // ===== FIQH & JURISPRUDENCE =====
  '00854': {
    id: '00854',
    titleAr: 'جامع الأحاديث (منابع فقه شيعه)',
    titleEn: 'Jami\' al-Ahadith',
    authorAr: 'آية الله البروجردي (رحمه الله)',
    authorEn: 'Ayatullah al-Burujirdi (ra)',
    volumes: 36,
    century: 14,
    deathYear: 1380,
    language: 'ar',
  },
  '01552': {
    id: '01552',
    titleAr: 'السرائر',
    titleEn: 'Al-Sara\'ir',
    authorAr: 'ابن إدريس الحلي (رحمه الله)',
    authorEn: 'Ibn Idris al-Hilli (ra)',
    volumes: 3,
    century: 6,
    deathYear: 598,
    language: 'ar',
  },
  '10848': {
    id: '10848',
    titleAr: 'موسوعة ابن إدريس الحلي',
    titleEn: 'Mawsu\'at Ibn Idris al-Hilli',
    authorAr: 'ابن إدريس الحلي (رحمه الله)',
    authorEn: 'Ibn Idris al-Hilli (ra)',
    volumes: 17,
    century: 6,
    deathYear: 598,
    language: 'ar',
  },
  '00694': {
    id: '00694',
    titleAr: 'الفصول المهمة',
    titleEn: 'Al-Fusul al-Muhimma',
    authorAr: 'الحر العاملي (رحمه الله)',
    authorEn: 'Al-Hurr al-Amili (ra)',
    volumes: 3,
    century: 11,
    deathYear: 1104,
    language: 'ar',
  },
  '00902': {
    id: '00902',
    titleAr: 'إثبات الهداة بالنصوص والمعجزات',
    titleEn: 'Ithbat al-Hudat',
    authorAr: 'الحر العاملي (رحمه الله)',
    authorEn: 'Al-Hurr al-Amili (ra)',
    volumes: 5,
    century: 11,
    deathYear: 1104,
    language: 'ar',
  },
  '00476': {
    id: '00476',
    titleAr: 'هداية الأمة إلى أحكام الأئمة',
    titleEn: 'Hidayat al-Umma',
    authorAr: 'الحر العاملي (رحمه الله)',
    authorEn: 'Al-Hurr al-Amili (ra)',
    volumes: 8,
    century: 11,
    deathYear: 1104,
    language: 'ar',
  },

  // ===== THEOLOGY & AQEEDAH =====
  '01266': {
    id: '01266',
    titleAr: 'غاية المرام',
    titleEn: 'Ghayat al-Maram',
    authorAr: 'السيد هاشم البحراني (رحمه الله)',
    authorEn: 'Sayyid Hashim al-Bahrani (ra)',
    volumes: 7,
    century: 11,
    deathYear: 1107,
    language: 'ar',
  },
  '86661': {
    id: '86661',
    titleAr: 'الشافي في الإمامة',
    titleEn: 'Al-Shafi fi al-Imama',
    authorAr: 'السيد المرتضى (رحمه الله)',
    authorEn: 'Sayyid al-Murtada (ra)',
    volumes: 4,
    century: 5,
    deathYear: 436,
    language: 'ar',
  },
  '03276': {
    id: '03276',
    titleAr: 'دلائل الصدق لنهج الحق',
    titleEn: 'Dala\'il al-Sidq',
    authorAr: 'الشيخ محمد حسن المظفر (رحمه الله)',
    authorEn: 'Sheikh Muhammad Hasan al-Muzaffar (ra)',
    volumes: 8,
    century: 14,
    deathYear: 1375,
    language: 'ar',
  },

  // ===== ETHICS & AKHLAQ =====
  '02607': {
    id: '02607',
    titleAr: 'الحياة',
    titleEn: 'Al-Hayat',
    authorAr: 'العلامة محمد رضا الحكيمي',
    authorEn: 'Allamah Muhammad Rida al-Hakimi',
    volumes: 6,
    century: 15,
    language: 'fa',
  },

  // ===== HADITH DICTIONARIES =====
  '02089': {
    id: '02089',
    titleAr: 'مجمع البحرين',
    titleEn: 'Majma\' al-Bahrayn',
    authorAr: 'الشيخ الطريحي (رحمه الله)',
    authorEn: 'Sheikh al-Turayhi (ra)',
    volumes: 6,
    century: 11,
    deathYear: 1085,
    language: 'ar',
  },
  '02384': {
    id: '02384',
    titleAr: 'النهاية في غريب الحديث',
    titleEn: 'Al-Nihaya fi Gharib al-Hadith',
    authorAr: 'ابن الأثير',
    authorEn: 'Ibn al-Athir',
    volumes: 5,
    century: 7,
    deathYear: 606,
    language: 'ar',
  },
  '00779': {
    id: '00779',
    titleAr: 'الفائق في غريب الحديث',
    titleEn: 'Al-Fa\'iq fi Gharib al-Hadith',
    authorAr: 'الزمخشري',
    authorEn: 'Al-Zamakhshari',
    volumes: 4,
    century: 6,
    deathYear: 538,
    language: 'ar',
  },

  // ===== TRANSLATIONS (PERSIAN) =====
  '02695': {
    id: '02695',
    titleAr: 'من لا يحضره الفقيه (ترجمة فارسي)',
    titleEn: 'Man La Yahduruhu al-Faqih (Persian)',
    authorAr: 'الشيخ الصدوق (رحمه الله)',
    authorEn: 'Sheikh al-Saduq (ra)',
    volumes: 6,
    language: 'fa',
  },
  '02647': {
    id: '02647',
    titleAr: 'أصول الكافي (ترجمة كمره‌اي)',
    titleEn: 'Usul al-Kafi (Kamarei Translation)',
    authorAr: 'الشيخ الكليني (رحمه الله)',
    authorEn: 'Sheikh al-Kulayni (ra)',
    volumes: 6,
    language: 'fa',
  },
  '02646': {
    id: '02646',
    titleAr: 'أصول الكافي (ترجمة مصطفوي)',
    titleEn: 'Usul al-Kafi (Mustafawi Translation)',
    authorAr: 'الشيخ الكليني (رحمه الله)',
    authorEn: 'Sheikh al-Kulayni (ra)',
    volumes: 4,
    language: 'fa',
  },
  '14926': {
    id: '14926',
    titleAr: 'فروع الكافي (ترجمة رحيميان)',
    titleEn: 'Furu\' al-Kafi (Rahimian Translation)',
    authorAr: 'الشيخ الكليني (رحمه الله)',
    authorEn: 'Sheikh al-Kulayni (ra)',
    volumes: 10,
    language: 'fa',
  },
  '02328': {
    id: '02328',
    titleAr: 'الاحتجاج (ترجمة فارسي)',
    titleEn: 'Al-Ihtijaj (Persian)',
    authorAr: 'الشيخ الطبرسي (رحمه الله)',
    authorEn: 'Sheikh al-Tabrisi (ra)',
    volumes: 2,
    language: 'fa',
  },

  // ===== AMALI & LECTURES =====
  '19236': {
    id: '19236',
    titleAr: 'ترتيب الأمالي',
    titleEn: 'Tartib al-Amali',
    authorAr: 'الشيخ محمد جواد المحمودي',
    authorEn: 'Sheikh Muhammad Jawad al-Mahmudi',
    volumes: 1,
    century: 15,
    language: 'ar',
  },
  '00978': {
    id: '00978',
    titleAr: 'عوالم العلوم',
    titleEn: '\'Awalim al-\'Ulum',
    authorAr: 'الشيخ عبد الله البحراني (رحمه الله)',
    authorEn: 'Sheikh Abdullah al-Bahrani (ra)',
    volumes: 26,
    century: 12,
    deathYear: 1130,
    language: 'ar',
  },

  // ===== HERITAGE & COLLECTIONS =====
  '18141': {
    id: '18141',
    titleAr: 'ميراث حديث شيعه',
    titleEn: 'Mirath Hadith Shia',
    authorAr: 'الشيخ مهدي مهريزي',
    authorEn: 'Sheikh Mahdi Mehrizi',
    volumes: 16,
    century: 15,
    language: 'fa',
  },
  '01500': {
    id: '01500',
    titleAr: 'عوالي اللئالي',
    titleEn: '\'Awali al-La\'ali',
    authorAr: 'ابن أبي جمهور الأحسائي (رحمه الله)',
    authorEn: 'Ibn Abi Jumhur al-Ahsa\'i (ra)',
    volumes: 4,
    century: 9,
    deathYear: 906,
    language: 'ar',
  },

  // ===== LETTERS & CORRESPONDENCE =====
  '03614': {
    id: '03614',
    titleAr: 'مكاتيب الأئمة عليهم السلام',
    titleEn: 'Makatib al-A\'imma',
    authorAr: 'الشيخ علي الأحمدي الميانجي',
    authorEn: 'Sheikh Ali al-Ahmadi al-Miyanji',
    volumes: 5,
    century: 15,
    language: 'ar',
  },
  '02346': {
    id: '02346',
    titleAr: 'مكاتيب الرسول (ص)',
    titleEn: 'Makatib al-Rasul',
    authorAr: 'الشيخ علي الأحمدي الميانجي',
    authorEn: 'Sheikh Ali al-Ahmadi al-Miyanji',
    volumes: 3,
    century: 15,
    language: 'ar',
  },

  // ===== ANWAR SERIES (JAZA\'IRI) =====
  '18219': {
    id: '18219',
    titleAr: 'الأنوار النعمانية',
    titleEn: 'Al-Anwar al-Nu\'maniyya',
    authorAr: 'السيد نعمة الله الجزائري (رحمه الله)',
    authorEn: 'Sayyid Ni\'matullah al-Jaza\'iri (ra)',
    volumes: 4,
    century: 12,
    deathYear: 1112,
    language: 'ar',
  },
  '03607': {
    id: '03607',
    titleAr: 'كشف الأسرار',
    titleEn: 'Kashf al-Asrar',
    authorAr: 'السيد نعمة الله الجزائري (رحمه الله)',
    authorEn: 'Sayyid Ni\'matullah al-Jaza\'iri (ra)',
    volumes: 1,
    century: 12,
    deathYear: 1112,
    language: 'ar',
  },
  '14053': {
    id: '14053',
    titleAr: 'عقود المرجان في تفسير القرآن',
    titleEn: '\'Uqud al-Marjan',
    authorAr: 'السيد نعمة الله الجزائري (رحمه الله)',
    authorEn: 'Sayyid Ni\'matullah al-Jaza\'iri (ra)',
    volumes: 1,
    century: 12,
    deathYear: 1112,
    language: 'ar',
  },

  // ===== MAJLISI FAMILY WORKS =====
  '10835': {
    id: '10835',
    titleAr: 'روضة المتقين',
    titleEn: 'Rawdat al-Muttaqin',
    authorAr: 'المولى محمد تقي المجلسي (رحمه الله)',
    authorEn: 'Mulla Muhammad Taqi al-Majlisi (ra)',
    volumes: 14,
    century: 11,
    deathYear: 1070,
    language: 'ar',
  },
  '03632': {
    id: '03632',
    titleAr: 'لوامع صاحبقراني',
    titleEn: 'Lawami\' Sahibqarani',
    authorAr: 'المولى محمد تقي المجلسي (رحمه الله)',
    authorEn: 'Mulla Muhammad Taqi al-Majlisi (ra)',
    volumes: 8,
    century: 11,
    deathYear: 1070,
    language: 'fa',
  },

  // ===== OTHER IMPORTANT WORKS =====
  '02325': {
    id: '02325',
    titleAr: 'فضائل الخمسة من الصحاح الستة',
    titleEn: 'Fada\'il al-Khamsa',
    authorAr: 'السيد مرتضى الفيروز آبادي',
    authorEn: 'Sayyid Murtada Firuzabadi',
    volumes: 3,
    century: 15,
    language: 'ar',
  },
  '119407': {
    id: '119407',
    titleAr: 'المستدرك الثاني لوسائل الشيعة',
    titleEn: 'Al-Mustadrak al-Thani',
    authorAr: 'الشيخ محمود قانصوه',
    authorEn: 'Sheikh Mahmud Qansuah',
    volumes: 5,
    century: 15,
    language: 'ar',
  },
  '01998': {
    id: '01998',
    titleAr: 'الجوهر الثمين',
    titleEn: 'Al-Jawhar al-Thamin',
    authorAr: 'السيد عبد الله شبر (رحمه الله)',
    authorEn: 'Sayyid Abdullah Shubbar (ra)',
    volumes: 6,
    century: 13,
    deathYear: 1242,
    language: 'ar',
  },
  '14965': {
    id: '14965',
    titleAr: 'لآلئ الأخبار',
    titleEn: 'La\'ali al-Akhbar',
    authorAr: 'المولى محمد نبي التويسركاني (رحمه الله)',
    authorEn: 'Mulla Muhammad Nabi al-Tuwaysirkani (ra)',
    volumes: 5,
    century: 13,
    deathYear: 1253,
    language: 'ar',
  },
};

// Get book display title with author
export function getBookDisplayName(bookId: string, language: 'en' | 'ar'): { title: string; author: string } {
  const metadata = BOOK_METADATA[bookId];
  if (metadata) {
    return {
      title: language === 'ar' ? metadata.titleAr : metadata.titleEn,
      author: language === 'ar' ? metadata.authorAr : metadata.authorEn,
    };
  }
  // Fallback for unknown books
  return {
    title: bookId,
    author: '',
  };
}

// Get full formatted display: "Title - Author"
export function getFormattedBookName(bookId: string, language: 'en' | 'ar'): string {
  const { title, author } = getBookDisplayName(bookId, language);
  if (author) {
    return `${title} - ${author}`;
  }
  return title;
}

// Check if book has metadata
export function hasBookMetadata(bookId: string): boolean {
  return bookId in BOOK_METADATA;
}
